# Generated by Django 5.2.3 on 2025-06-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('min_stock', models.PositiveIntegerField(verbose_name='Минимальный остаток')),
                ('current_stock', models.PositiveIntegerField(verbose_name='Текущий остаток')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отдела')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название принтера')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.department')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_used', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.cartridge')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.printer')),
            ],
        ),
    ]
