# Generated by Django 5.2.3 on 2025-06-23 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Модель принтера'),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='PrinterCartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.cartridge')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.printer')),
            ],
            options={
                'verbose_name': 'Совместимость',
                'verbose_name_plural': 'Совместимости',
            },
        ),
    ]
