# Generated by Django 5.2.3 on 2025-06-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0002_alter_printer_name_alter_usagerecord_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='min_stock',
        ),
        migrations.CreateModel(
            name='CartridgeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(verbose_name='Остаток')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.cartridge')),
            ],
        ),
        migrations.CreateModel(
            name='CartridgeMinStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_stock', models.PositiveIntegerField(verbose_name='Минимальный остаток')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.cartridge')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.department')),
            ],
        ),
    ]
